name: CD - Simulação de Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Deploy...
      run: |
        echo "🚀 Iniciando processo de deploy..."
        sleep 3
        echo "✅ Deploy realizado com sucesso!"
